[colors.primary]
background = "#08080b"
foreground = "#ffffff"

[colors.cursor]
cursor = "#ff1378"

[colors.selection]
text = "CellForeground"
background = "#ff1378"

[colors.normal]
black = "#000000"
red = "#00f2ff"
green = "#00f2ff"
yellow = "#e0af68"
blue = "#6eff63"
magenta = "#ff006a"
cyan = "#6eff63"
white = "#787c99"

[colors.bright]
black = "#61a4ad"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"
